### ISSUE TITLE
Hardhat Plugin Issues

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#717] opened 2024-03-15 14:40 UTC
A user is reporting issues on the `sdk-hardhat-plugin` where they are receiving the following error.

`Caused by: Error: Method 'eth_blockNumber' failed: Error while getting the latest block number.`

`_HardhatPluginError: Error on request - eth_blockNumber
@repo/contracts:test:hardhat:       at HardhatVechainProvider.buildHardhatErrorFunctionCallback (/Users/danrusnac/Work/vechain/b3tr/b3tr/node_modules/@vechain/sdk-hardhat-plugin/dist/index.js:109905:26)
@repo/contracts:test:hardhat:       at HardhatVechainProvider.request (/Users/danrusnac/Work/vechain/b3tr/b3tr/node_modules/@vechain/sdk-provider/dist/index.js:3361:18)
@repo/contracts:test:hardhat:       at processTicksAndRejections (node:internal/process/task_queues:95:5)
@repo/contracts:test:hardhat:       at async HardhatVechainProvider.send (/Users/danrusnac/Work/vechain/b3tr/b3tr/node_modules/@vechain/sdk-provider/dist/index.js:3287:12)
@repo/contracts:test:hardhat:       at async HardhatEthersProvider.getBlockNumber (/Users/danrusnac/Work/vechain/b3tr/b3tr/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:134:25)
@repo/contracts:test:hardhat:       at async HardhatEthersSigner.sendTransaction (/Users/danrusnac/Work/vechain/b3tr/b3tr/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:122:25)
@repo/contracts:test:hardhat:       at async ContractFactory.deploy (/Users/danrusnac/Work/vechain/b3tr/b3tr/node_modules/ethers/src.ts/contract/factory.ts:111:24)
@repo/contracts:test:hardhat:       at async getOrDeployContractInstances (/Users/danrusnac/Work/vechain/b3tr/b3tr/packages/contracts/test/helpers/deploy.ts:58:16)
@repo/contracts:test:hardhat:       at async Context.<anonymous> (/Users/danrusnac/Work/vechain/b3tr/b3tr/packages/contracts/test/XApps.test.ts:117:59)`

`Error in plugin @vechain/sdk-hardhat-plugin: Error on request - hardhat_getStackTraceFailuresCount`

Tasks:
- Identify and fix the root cause of the issue

**Comment by rodolfopietro97** [comment] 2024-03-20 10:13
@nwbrettski This issue was related to:
* The fact that all ethers function are not implemented
* The fact that if network name doesn't contains 'vechain' some issues are caused

**Comment by nwbrettski** [comment] 2024-03-25 10:55
@rodolfopietro97 can this issue be closed then or is there something that we need to do to prevent other users from hitting this same issue?

**Comment by victhorbi** [comment] 2024-04-18 13:15
The issue is solved, we are closing the issue. 
Please, @rodolfopietro97 can you add a small comment to explain how it was solved?

**Closed by victhorbi** 2024-04-18 13:15 UTC
Labels: Type: Bug, Size: Small, Priority: High

**Comment by rodolfopietro97** [comment] 2024-04-19 08:49
@victhorbi  @nwbrettski Sorry guys, I forgot to comment this issue. This seems to be solved because this problem was caused by previous hardhat issue fixed into this task #660
