### ISSUE TITLE
feat :: Multiclauses support scouting

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#1030] opened 2024-07-09 12:42 UTC
Understand and study how to implement the multi clauses into our sdk.
For example Understand if it is possible to use multi clause into ethers factories for hardhat.

DOD:

- [ ] Study better the multiclause
- [ ] Understand where it can be implemented into SDK

**Comment by victhorbi** [comment] 2024-08-14 13:27
Duplicate of #1003

**Closed by victhorbi** 2024-08-14 13:27 UTC
Labels: Type: Research, Size: Large, Priority: Low
